## Pruebas con numpy

In [2]:
import numpy as np

In [3]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
%%timeit
my_arr = np.arange(1000000)
for _ in range(10): my_arr2 = my_arr * 2

16.9 ms ± 862 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%%timeit
my_list = list(range(100000))
for _ in range(10): my_list2 = [x*2 for x in my_list]

54.4 ms ± 11.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Inferencia de tipos

In [7]:
arr = np.array([1,2,3.4,8+3j])
arr

array([1. +0.j, 2. +0.j, 3.4+0.j, 8. +3.j])

In [8]:
arr.dtype

dtype('complex128')

In [9]:
arr2 = np.array(['1','2','3','8'], dtype="u1")
arr2

array([1, 2, 3, 8], dtype=uint8)

In [12]:
arr3 = np.array(('1','2','3','8'), dtype="u1")
arr3

array([1, 2, 3, 8], dtype=uint8)

In [13]:
arr4 = arr3.astype(np.int16)
arr4

array([1, 2, 3, 8], dtype=int16)

In [14]:
m = np.arange(25).reshape(5,-1)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
m = np.arange(50).reshape(2,5,5)
m

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [16]:
m.shape

(2, 5, 5)

In [17]:
m.ndim

3

In [19]:
m2 = np.empty_like(m)
m2

array([[[4128860, 6029375, 3801187, 7667804, 6619251],
        [7536754, 6357084, 7602286, 7209071, 6357084],
        [7340144, 6357092, 6357108, 7471196, 6357103],
        [6881389, 6750318, 7340124, 7602297, 7274600],
        [6029422, 7929968, 6815860, 7209071, 3670067]],

       [[7536732, 7602281, 2949221, 6357104, 7012451],
        [6750305, 7536741, 7602268, 6357106, 7602281],
        [6619244, 7536756, 6488156, 7209071, 6881382],
        [6029415, 6226015, 7209065, 7602281, 6226015],
        [7340078,     121, 6946816, 7274611,     110]]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arr1 = np.arange(12)
arr2 = np.arange(0,24,2)
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [23]:
arr1 + arr2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [24]:
arr3 = arr2 * 10
arr3

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220])

In [28]:
arr2[(arr2 >= 5) & (arr2 <= 10)]

array([ 6,  8, 10])

In [26]:
arr2 > 5

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [29]:
arr1 < arr2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])