## Pruebas con numpy

In [2]:
import numpy as np

In [3]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
%%timeit
my_arr = np.arange(1000000)
for _ in range(10): my_arr2 = my_arr * 2

16.9 ms ± 862 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%%timeit
my_list = list(range(100000))
for _ in range(10): my_list2 = [x*2 for x in my_list]

54.4 ms ± 11.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Inferencia de tipos

In [7]:
arr = np.array([1,2,3.4,8+3j])
arr

array([1. +0.j, 2. +0.j, 3.4+0.j, 8. +3.j])

In [8]:
arr.dtype

dtype('complex128')

In [9]:
arr2 = np.array(['1','2','3','8'], dtype="u1")
arr2

array([1, 2, 3, 8], dtype=uint8)

In [12]:
arr3 = np.array(('1','2','3','8'), dtype="u1")
arr3

array([1, 2, 3, 8], dtype=uint8)

In [13]:
arr4 = arr3.astype(np.int16)
arr4

array([1, 2, 3, 8], dtype=int16)

In [14]:
m = np.arange(25).reshape(5,-1)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
m = np.arange(50).reshape(2,5,5)
m

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])