## Pruebas con numpy

In [2]:
import numpy as np

In [3]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
%%timeit
my_arr = np.arange(1000000)
for _ in range(10): my_arr2 = my_arr * 2

16.9 ms ± 862 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%%timeit
my_list = list(range(100000))
for _ in range(10): my_list2 = [x*2 for x in my_list]

54.4 ms ± 11.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Inferencia de tipos

In [7]:
arr = np.array([1,2,3.4,8+3j])
arr

array([1. +0.j, 2. +0.j, 3.4+0.j, 8. +3.j])

In [8]:
arr.dtype

dtype('complex128')

In [9]:
arr2 = np.array(['1','2','3','8'], dtype="u1")
arr2

array([1, 2, 3, 8], dtype=uint8)

In [12]:
arr3 = np.array(('1','2','3','8'), dtype="u1")
arr3

array([1, 2, 3, 8], dtype=uint8)

In [13]:
arr4 = arr3.astype(np.int16)
arr4

array([1, 2, 3, 8], dtype=int16)

In [14]:
m = np.arange(25).reshape(5,-1)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
m = np.arange(50).reshape(2,5,5)
m

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [16]:
m.shape

(2, 5, 5)

In [17]:
m.ndim

3

In [19]:
m2 = np.empty_like(m)
m2

array([[[4128860, 6029375, 3801187, 7667804, 6619251],
        [7536754, 6357084, 7602286, 7209071, 6357084],
        [7340144, 6357092, 6357108, 7471196, 6357103],
        [6881389, 6750318, 7340124, 7602297, 7274600],
        [6029422, 7929968, 6815860, 7209071, 3670067]],

       [[7536732, 7602281, 2949221, 6357104, 7012451],
        [6750305, 7536741, 7602268, 6357106, 7602281],
        [6619244, 7536756, 6488156, 7209071, 6881382],
        [6029415, 6226015, 7209065, 7602281, 6226015],
        [7340078,     121, 6946816, 7274611,     110]]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arr1 = np.arange(12)
arr2 = np.arange(0,24,2)
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [23]:
arr1 + arr2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [24]:
arr3 = arr2 * 10
arr3

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220])

In [28]:
arr2[(arr2 >= 5) & (arr2 <= 10)]

array([ 6,  8, 10])

In [26]:
arr2 > 5

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [29]:
arr1 < arr2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [30]:
m = np.arange(25).reshape(5,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
m[1:-1,1:-1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [32]:
m[0]

array([0, 1, 2, 3, 4])

In [33]:
m[[0,2,3]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
m[[3,2,1]]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

In [35]:
m.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [36]:
m[[True,False,True,False,True]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [38]:
x = np.random.randn(5)
x = x * 10
x

array([ -3.78069116, -10.90256958,   2.23597343,   8.1199112 ,
        -7.33122886])

In [39]:
y = np.random.randint(1,20,5)
y

array([17, 12,  6,  5, 14])

In [40]:
np.maximum(x,y)

array([17.       , 12.       ,  6.       ,  8.1199112, 14.       ])

In [41]:
np.ceil([1.1,3.5,6.7,5.5])

array([2., 4., 7., 6.])

In [44]:
np.ceil((1.1,3.5,6.7,5.5))

array([2., 4., 7., 6.])

In [45]:
np.ceil({1.1,3.5,6.7,5.5})

TypeError: must be real number, not set

In [52]:
matriz = np.random.randn(4,6)
matriz

array([[ 0.37528578,  0.13502269, -0.13337173,  1.36050938,  0.24342967,
         0.08260636],
       [-0.27371657,  0.97523714,  1.94609459, -0.52499824,  0.15164921,
        -0.05779974],
       [ 0.23424168, -0.28880191, -0.72932655, -0.18497337, -0.229325  ,
        -2.00901138],
       [-1.86532679, -0.54767533, -1.12379029,  0.47347775, -0.29840161,
         1.03803224]])

In [53]:
m2 = np.where(matriz > 0, matriz, 0)
m2

array([[0.37528578, 0.13502269, 0.        , 1.36050938, 0.24342967,
        0.08260636],
       [0.        , 0.97523714, 1.94609459, 0.        , 0.15164921,
        0.        ],
       [0.23424168, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.47347775, 0.        ,
        1.03803224]])

In [54]:
m2 = np.where(matriz > 0, matriz, np.round(matriz,2))
m2

array([[ 0.37528578,  0.13502269, -0.13      ,  1.36050938,  0.24342967,
         0.08260636],
       [-0.27      ,  0.97523714,  1.94609459, -0.52      ,  0.15164921,
        -0.06      ],
       [ 0.23424168, -0.29      , -0.73      , -0.18      , -0.23      ,
        -2.01      ],
       [-1.87      , -0.55      , -1.12      ,  0.47347775, -0.3       ,
         1.03803224]])

In [55]:
m2.sum()

-1.2444135269648424

In [56]:
m2.sum(axis=0)

array([-1.53047255,  0.27025983, -0.03390541,  1.13398713, -0.13492112,
       -0.9493614 ])

In [57]:
m2.sum(axis=1)

array([ 2.06685387,  2.22298094, -3.20575832, -2.32849001])

In [59]:
# Contar los valores mayores de cero
(m2 > 0).sum()

11

In [62]:
x = np.random.randint (0, 50,1000)
y = x + np.random.normal (0, 10,1000)
m = np.corrcoef(x,y)
m[0][1] * 100

83.49378754701056

In [63]:
from collections import Counter

x = np.random.randint (0, 20, 1000)
c = Counter(x)
c

Counter({16: 52,
         2: 69,
         0: 40,
         3: 46,
         5: 48,
         1: 50,
         17: 45,
         13: 54,
         19: 41,
         8: 39,
         4: 52,
         18: 53,
         7: 60,
         6: 46,
         10: 54,
         9: 45,
         14: 52,
         12: 50,
         11: 50,
         15: 54})

In [64]:
m2

array([[ 0.37528578,  0.13502269, -0.13      ,  1.36050938,  0.24342967,
         0.08260636],
       [-0.27      ,  0.97523714,  1.94609459, -0.52      ,  0.15164921,
        -0.06      ],
       [ 0.23424168, -0.29      , -0.73      , -0.18      , -0.23      ,
        -2.01      ],
       [-1.87      , -0.55      , -1.12      ,  0.47347775, -0.3       ,
         1.03803224]])

In [65]:
r = m2 > 0.3
r

array([[ True, False, False,  True, False, False],
       [False,  True,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False,  True]])

In [66]:
r.any()

True

In [67]:
arr1 = np.random.randn(10)
arr1

array([ 0.15780983,  0.93558107, -0.12489463,  1.23786341, -1.00859287,
        1.03843281, -0.563701  ,  2.31550318, -0.23414164, -0.4587266 ])

In [68]:
arr2 = np.sort(arr1)
arr2

array([-1.00859287, -0.563701  , -0.4587266 , -0.23414164, -0.12489463,
        0.15780983,  0.93558107,  1.03843281,  1.23786341,  2.31550318])

In [69]:
arr1

array([ 0.15780983,  0.93558107, -0.12489463,  1.23786341, -1.00859287,
        1.03843281, -0.563701  ,  2.31550318, -0.23414164, -0.4587266 ])

In [70]:
arr1.sort()

In [71]:
arr1

array([-1.00859287, -0.563701  , -0.4587266 , -0.23414164, -0.12489463,
        0.15780983,  0.93558107,  1.03843281,  1.23786341,  2.31550318])

In [74]:
m = np.random.randint(1,50, (20, 25))
m2 = np.random.randint(1,50, (40, 100))

In [75]:
np.savez_compressed("ficheros/matrices.npz", m=m, m2=m2)

In [76]:
resul = np.load("ficheros/matrices.npz")
m2_2 = resul["m2"]

In [77]:
np.all(m2 == m2_2)

True

In [79]:
np.savetxt("ficheros/matrices.csv", m2, delimiter=";", fmt="%d")