## Pruebas con la librería numpy

In [1]:
import numpy as np

In [2]:
%%timeit

L = list(range(1000000))
for _ in range(10): L2 = [i*2 for i in L]

754 ms ± 58.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%%timeit

arr = np.arange(1000000)
for _ in range(10): arr2 = arr * 10

16.8 ms ± 407 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
arr = np.array([1,2,3,4,5,9.5])
arr

array([1. , 2. , 3. , 4. , 5. , 9.5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

float64
(6,)
1


In [7]:
arr = np.array([1,2,3,4], dtype=np.uint8)
arr2 = np.array([1,2,3,4], dtype="u2")

print(arr, arr.dtype)
print(arr2, arr2.dtype)



[1 2 3 4] uint8
[1 2 3 4] uint16


In [8]:
arr3 = np.array(["1","2","3","4"], dtype=np.uint8)
print(arr3, arr3.dtype)

[1 2 3 4] uint8


In [10]:
arr = np.array([1,"2",3,4,5+8j,9.5])
arr

array(['1', '2', '3', '4', '(5+8j)', '9.5'], dtype='<U64')

In [11]:
t = np.zeros((5,6))
t

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
t = np.empty((5,6))
t

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
t2 = np.full_like(t, fill_value=5)
t2

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

In [16]:
arr = np.random.randint(1,20, 25)
arr

array([ 8, 11, 14, 10, 11, 10, 11, 14, 12, 13,  6, 15, 13,  7, 13, 14, 10,
       10, 11, 17,  4,  7,  2,  4,  6])

In [17]:
arr2 = arr + 10
arr2

array([18, 21, 24, 20, 21, 20, 21, 24, 22, 23, 16, 25, 23, 17, 23, 24, 20,
       20, 21, 27, 14, 17, 12, 14, 16])

In [20]:
arr2 > 15

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False, False,  True])

In [21]:
arr = np.random.randint(1,20, 20)
arr

array([14,  6,  6,  5, 11, 15, 18,  9,  4,  5,  7,  4,  7, 18, 14, 14, 10,
       11, 16,  1])

In [22]:
arr2 = np.random.randint(1,20, 20)
arr2

array([12,  9,  5,  3, 19,  1,  5, 16, 10, 12,  9, 11, 16,  3,  9,  3, 18,
       11,  6, 19])

In [23]:
np.maximum(arr, arr2)

array([14,  9,  6,  5, 19, 15, 18, 16, 10, 12,  9, 11, 16, 18, 14, 14, 18,
       11, 16, 19])

In [24]:
np.minimum(arr, arr2)

array([12,  6,  5,  3, 11,  1,  5,  9,  4,  5,  7,  4,  7,  3,  9,  3, 10,
       11,  6,  1])

In [25]:
(arr2 > 10).sum()

9

In [26]:
arr2[arr2 > 10]

array([12, 19, 16, 12, 11, 16, 18, 11, 19])

In [27]:
arr2[(arr2 > 5) & (arr2 < 10)]

array([9, 9, 9, 6])

In [28]:
arr2[arr2 > 10]=10
arr2

array([10,  9,  5,  3, 10,  1,  5, 10, 10, 10,  9, 10, 10,  3,  9,  3, 10,
       10,  6, 10])

In [29]:
m = np.random.randint(1,50, 25).reshape(5,-1)
m

array([[ 2, 34, 21,  9, 46],
       [30, 18, 47,  2,  3],
       [17, 26, 10, 35, 22],
       [37, 10, 27, 13,  4],
       [38,  8, 15,  3, 35]])

In [30]:
m[1:-1,1:-1]

array([[18, 47,  2],
       [26, 10, 35],
       [10, 27, 13]])

In [31]:
m[[True, True, False, False, False]]

array([[ 2, 34, 21,  9, 46],
       [30, 18, 47,  2,  3]])

In [32]:
m[[1,3,0]]

array([[30, 18, 47,  2,  3],
       [37, 10, 27, 13,  4],
       [ 2, 34, 21,  9, 46]])

In [33]:
m

array([[ 2, 34, 21,  9, 46],
       [30, 18, 47,  2,  3],
       [17, 26, 10, 35, 22],
       [37, 10, 27, 13,  4],
       [38,  8, 15,  3, 35]])

In [34]:
np.where(m>30,30,m)

array([[ 2, 30, 21,  9, 30],
       [30, 18, 30,  2,  3],
       [17, 26, 10, 30, 22],
       [30, 10, 27, 13,  4],
       [30,  8, 15,  3, 30]])

In [35]:
m.sum()

512

In [36]:
m.sum(axis=0)

array([124,  96, 120,  62, 110])

In [37]:
m.sum(axis=1)

array([112, 100, 110,  91,  99])

In [39]:
m = np.random.randint(1,50, 25)
print(m)
np.cumsum(m)

[23 42 24 25 44 32 20 32 27 44 26 40 22 36 27  5  8 25  3 19 31 36 25  8
 45]


array([ 23,  65,  89, 114, 158, 190, 210, 242, 269, 313, 339, 379, 401,
       437, 464, 469, 477, 502, 505, 524, 555, 591, 616, 624, 669],
      dtype=int32)

In [40]:
x = np.random.randint (0, 50, 1000)
y = x + np.random.normal (0, 10, 1000)

t = np.corrcoef(x,y)

In [41]:
t

array([[1.        , 0.80572369],
       [0.80572369, 1.        ]])

In [42]:
round(t[1][0] * 100,2)

80.57

In [43]:
m

array([23, 42, 24, 25, 44, 32, 20, 32, 27, 44, 26, 40, 22, 36, 27,  5,  8,
       25,  3, 19, 31, 36, 25,  8, 45])

In [45]:
np.any(m>30)

True

In [46]:
np.all(m>30)

False

In [58]:
m = np.random.randint(1,50,200).reshape(20,-1)
m

array([[22, 43, 25, 17,  6, 45, 40, 30,  4, 38],
       [13, 10, 45, 11, 13,  3, 27, 42, 46, 16],
       [21, 28, 38, 32, 43, 38, 10, 17, 15, 22],
       [ 5, 23, 46, 46,  7, 12, 14, 34, 46, 46],
       [14, 31, 42, 44, 27, 19, 35, 43, 25,  6],
       [19, 39, 39, 42, 41, 44,  3, 23,  8, 36],
       [45, 16, 30, 42, 15, 48, 42, 13, 31, 48],
       [27, 38, 39,  1,  3, 30, 38, 27,  9, 42],
       [18, 43, 36, 31,  7, 12, 36, 13, 25, 16],
       [16, 20, 48, 22, 25, 19,  6, 34, 16, 15],
       [42, 20,  2,  9, 12, 37, 43, 21,  9, 25],
       [20, 38, 27, 37, 17, 40, 46, 39, 42,  6],
       [24,  2, 30, 45, 15, 26, 17, 40, 34, 38],
       [ 3, 19, 47, 31, 20, 10, 25,  7,  3, 23],
       [28, 44, 45, 33, 37, 23, 35, 43,  7, 49],
       [11, 17, 26,  8, 35,  5,  8, 23, 42,  8],
       [ 5, 25, 20, 11, 26, 29,  4, 41, 28,  2],
       [45, 33, 25, 14,  5, 36, 19, 36, 33, 11],
       [45,  4, 17, 34,  1, 24, 30, 44,  8, 20],
       [40, 38, 36, 49, 49, 44, 15, 18, 47, 44]])

In [59]:
np.savetxt("../ficheros/matriz.csv", m, delimiter=';', fmt="%d")

In [60]:
m2 = np.random.randint(1,50,200).reshape(20,-1)
m2 = m2 * 0.75
m2

array([[32.25, 30.  , 22.5 , 16.5 , 23.25,  3.  , 27.  , 10.5 ,  8.25,
         9.  ],
       [36.  , 26.25, 18.  , 18.75,  5.25, 21.  , 10.5 , 36.  , 12.  ,
        29.25],
       [ 9.  , 27.  , 30.  , 24.75,  8.25, 29.25, 18.75, 18.75,  3.  ,
         0.75],
       [33.  , 19.5 ,  9.  , 11.25, 27.75,  5.25,  6.  ,  3.  , 12.75,
        14.25],
       [13.5 , 21.75,  5.25, 12.75, 36.75,  6.75,  5.25, 30.75, 33.  ,
        25.5 ],
       [ 5.25,  9.  , 27.  , 33.  , 35.25,  6.  ,  5.25, 35.25, 25.5 ,
         8.25],
       [30.75,  6.75, 24.  ,  4.5 , 11.25, 18.  ,  6.75, 15.75, 12.75,
        30.75],
       [28.5 , 12.75, 10.5 , 10.5 ,  3.75,  9.75, 14.25,  8.25, 14.25,
         3.  ],
       [19.5 ,  1.5 ,  2.25, 34.5 , 33.  , 14.25,  2.25, 21.  , 12.75,
        15.75],
       [33.  , 16.5 , 31.5 , 23.25, 32.25, 27.  , 18.  ,  6.  , 12.  ,
        21.75],
       [13.5 ,  5.25, 29.25, 28.5 , 21.75, 20.25, 30.75,  4.5 , 24.75,
        21.75],
       [30.  , 23.25, 33.75,  1.5 ,  6.75, 

In [61]:
np.savetxt("../ficheros/matriz.csv", m, delimiter=';', fmt="%.2f")

In [63]:
np.savez_compressed("../ficheros/matriz.npz", a=m, b=m2)


In [65]:
matrices = np.load("../ficheros/matriz.npz")
matrices["a"]

array([[22, 43, 25, 17,  6, 45, 40, 30,  4, 38],
       [13, 10, 45, 11, 13,  3, 27, 42, 46, 16],
       [21, 28, 38, 32, 43, 38, 10, 17, 15, 22],
       [ 5, 23, 46, 46,  7, 12, 14, 34, 46, 46],
       [14, 31, 42, 44, 27, 19, 35, 43, 25,  6],
       [19, 39, 39, 42, 41, 44,  3, 23,  8, 36],
       [45, 16, 30, 42, 15, 48, 42, 13, 31, 48],
       [27, 38, 39,  1,  3, 30, 38, 27,  9, 42],
       [18, 43, 36, 31,  7, 12, 36, 13, 25, 16],
       [16, 20, 48, 22, 25, 19,  6, 34, 16, 15],
       [42, 20,  2,  9, 12, 37, 43, 21,  9, 25],
       [20, 38, 27, 37, 17, 40, 46, 39, 42,  6],
       [24,  2, 30, 45, 15, 26, 17, 40, 34, 38],
       [ 3, 19, 47, 31, 20, 10, 25,  7,  3, 23],
       [28, 44, 45, 33, 37, 23, 35, 43,  7, 49],
       [11, 17, 26,  8, 35,  5,  8, 23, 42,  8],
       [ 5, 25, 20, 11, 26, 29,  4, 41, 28,  2],
       [45, 33, 25, 14,  5, 36, 19, 36, 33, 11],
       [45,  4, 17, 34,  1, 24, 30, 44,  8, 20],
       [40, 38, 36, 49, 49, 44, 15, 18, 47, 44]])

In [68]:
list(matrices.keys())

['a', 'b']