## Pruebas con la librería numpy

In [1]:
import numpy as np

In [2]:
%%timeit

L = list(range(1000000))
for _ in range(10): L2 = [i*2 for i in L]

754 ms ± 58.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%%timeit

arr = np.arange(1000000)
for _ in range(10): arr2 = arr * 10

16.8 ms ± 407 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
arr = np.array([1,2,3,4,5,9.5])
arr

array([1. , 2. , 3. , 4. , 5. , 9.5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

float64
(6,)
1


In [7]:
arr = np.array([1,2,3,4], dtype=np.uint8)
arr2 = np.array([1,2,3,4], dtype="u2")

print(arr, arr.dtype)
print(arr2, arr2.dtype)



[1 2 3 4] uint8
[1 2 3 4] uint16
