## Pruebas con la librería numpy

In [1]:
import numpy as np

In [2]:
%%timeit

L = list(range(1000000))
for _ in range(10): L2 = [i*2 for i in L]

754 ms ± 58.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%%timeit

arr = np.arange(1000000)
for _ in range(10): arr2 = arr * 10

16.8 ms ± 407 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
arr = np.array([1,2,3,4,5,9.5])
arr

array([1. , 2. , 3. , 4. , 5. , 9.5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

float64
(6,)
1


In [7]:
arr = np.array([1,2,3,4], dtype=np.uint8)
arr2 = np.array([1,2,3,4], dtype="u2")

print(arr, arr.dtype)
print(arr2, arr2.dtype)



[1 2 3 4] uint8
[1 2 3 4] uint16


In [8]:
arr3 = np.array(["1","2","3","4"], dtype=np.uint8)
print(arr3, arr3.dtype)

[1 2 3 4] uint8


In [10]:
arr = np.array([1,"2",3,4,5+8j,9.5])
arr

array(['1', '2', '3', '4', '(5+8j)', '9.5'], dtype='<U64')

In [11]:
t = np.zeros((5,6))
t

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
t = np.empty((5,6))
t

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
t2 = np.full_like(t, fill_value=5)
t2

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

In [16]:
arr = np.random.randint(1,20, 25)
arr

array([ 8, 11, 14, 10, 11, 10, 11, 14, 12, 13,  6, 15, 13,  7, 13, 14, 10,
       10, 11, 17,  4,  7,  2,  4,  6])

In [17]:
arr2 = arr + 10
arr2

array([18, 21, 24, 20, 21, 20, 21, 24, 22, 23, 16, 25, 23, 17, 23, 24, 20,
       20, 21, 27, 14, 17, 12, 14, 16])

In [20]:
arr2 > 15

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False, False,  True])