## Pruebas con la librería numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.0'

In [3]:
%%timeit
# Ejecución con una lista
L = list(range(1000000))
for _ in range(10): L = [x * 2 for x in L]

708 ms ± 19.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%%timeit
# Ejecución con un array de numpy
arr = np.arange(1000000)
for _ in range(10): arr = arr * 2

15.3 ms ± 62 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
a = np.array([1,2,3,5., 8])
a


array([1., 2., 3., 5., 8.])

In [6]:
b = np.array([12,3,5.,7+8j, 9])
b

array([12.+0.j,  3.+0.j,  5.+0.j,  7.+8.j,  9.+0.j])

In [7]:
a.dtype

dtype('float64')

In [8]:
b.dtype

dtype('complex128')

In [9]:
a.shape

(5,)

In [10]:
c = np.array([1,2,3,4,5,6], dtype="u1")
print(c)
print(c.dtype)

[1 2 3 4 5 6]
uint8


In [11]:
d = np.array(['1','2','3','4'], dtype=np.uint8)
d

array([1, 2, 3, 4], dtype=uint8)

Generación de matrices con numpy

In [12]:
t = tuple(range(10))
a = np.array(t)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a1 = np.arange(0,100,5)
a1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [14]:
a2 = np.zeros(10)
a2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
a3 = np.zeros((2,3,4))
a3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
m = np.ones_like(a3)
m

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
m2 = np.arange(25).reshape(5,-1)
m2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Operaciones con arrays

In [28]:
a = np.random.randint(1,50,20)
a

array([35, 25, 46,  6, 26, 26, 32,  2, 33, 10, 46, 38,  3, 29, 44, 27, 46,
        4, 21, 15])

In [29]:
b = np.random.randint(1,50,20)
b

array([39, 10,  1, 21, 31, 39, 49, 41, 22,  4,  5, 16, 15, 33, 28, 32, 10,
       21,  1,  1])

In [30]:
a + b

array([74, 35, 47, 27, 57, 65, 81, 43, 55, 14, 51, 54, 18, 62, 72, 59, 56,
       25, 22, 16])

In [31]:
a > 5

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True])

In [32]:
a[a > 5]

array([35, 25, 46,  6, 26, 26, 32, 33, 10, 46, 38, 29, 44, 27, 46, 21, 15])

In [34]:
a[(a >= 20) & (a <= 30)]

array([25, 26, 26, 29, 27, 21])

In [35]:
a[(a < 20) | (a > 30)]

array([35, 46,  6, 32,  2, 33, 10, 46, 38,  3, 44, 46,  4, 15])

Acceso a los elementos del array:

In [36]:
a[0]

35

In [37]:
a[:5]

array([35, 25, 46,  6, 26])

In [38]:
a.item(2)

46

In [39]:
a

array([35, 25, 46,  6, 26, 26, 32,  2, 33, 10, 46, 38,  3, 29, 44, 27, 46,
        4, 21, 15])

In [40]:
a[a > 40] = 40
a

array([35, 25, 40,  6, 26, 26, 32,  2, 33, 10, 40, 38,  3, 29, 40, 27, 40,
        4, 21, 15])

In [ ]:
m = np.random.randint(1,20, )