In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
%%timeit
L = list(range(1000000))
for _ in range(10): L2 = [x * 2 for x in L]

681 ms ± 26.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%%timeit
arr = np.arange(1000000)
for _ in range(10): arr2 = arr * 2

16 ms ± 210 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
arr1 = np.array([1, 5, 3, 2, 7.7])
print(arr1)
print(arr1.dtype)


[1.  5.  3.  2.  7.7]
float64


In [10]:
#arr1 = np.array(["1", "5", "3", "2", "7"], dtype="u1")
arr1 = np.array(["1", "5", "3", "2", "7"], dtype=np.uint8)
print(arr1)
print(arr1.dtype)

[1 5 3 2 7]
uint8


In [11]:
arr1.shape

(5,)

In [14]:
arr2 = np.arange(50).reshape(2,5,5)
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [15]:
arr3 = arr2.astype(np.float64)
arr3

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]],

       [[25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.]]])

In [19]:
arr4 = np.array((1,2,3,4,5))
arr4

array([1, 2, 3, 4, 5])

In [20]:
ceros = np.zeros((5,7))
ceros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [22]:
unos = np.ones_like(ceros)
unos

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

Operadores aritméticos y relacionales

In [23]:
arr1 = np.random.randint(1,25,15)
arr1

array([13, 19, 21, 24, 17, 16,  1, 16,  7, 13,  8, 18, 23, 19,  1])

In [24]:
arr2 = np.random.randint(1,25,15)
arr2

array([13, 10, 11, 15, 14, 15, 17,  1,  3, 20, 16,  6, 24,  2,  4])

In [25]:
arr1 + arr2

array([26, 29, 32, 39, 31, 31, 18, 17, 10, 33, 24, 24, 47, 21,  5])

In [26]:
arr1 > 10

array([ True,  True,  True,  True,  True,  True, False,  True, False,
        True, False,  True,  True,  True, False])

In [28]:
(arr1 > 10).sum()

11

Filtrar, slicing, modificar

In [29]:
arr1[arr1 > 10]

array([13, 19, 21, 24, 17, 16, 16, 13, 18, 23, 19])

In [30]:
arr1[arr1 <= 10]

array([1, 7, 8, 1])

In [31]:
arr1[[0,1,3,10]]

array([13, 19, 24,  8])

In [32]:
arr1

array([13, 19, 21, 24, 17, 16,  1, 16,  7, 13,  8, 18, 23, 19,  1])

In [33]:
arr1[arr1 > 20] = 20
arr1

array([13, 19, 20, 20, 17, 16,  1, 16,  7, 13,  8, 18, 20, 19,  1])

In [35]:
arr1[(arr1 >= 10) & (arr1 <= 16)]

array([13, 16, 16, 13])

In [36]:
m = np.random.randint(1,50, (5,5))
m

array([[33, 41, 45,  4, 15],
       [ 6, 20, 24,  5, 45],
       [34,  5, 38, 47, 39],
       [11, 42,  4, 35, 15],
       [31, 18, 15, 41, 35]])

In [37]:
# Quitar la primera y última fila y columna:
m[1:-1, 1:-1]

array([[20, 24,  5],
       [ 5, 38, 47],
       [42,  4, 35]])

In [39]:
m[[4,0,3]]

array([[31, 18, 15, 41, 35],
       [33, 41, 45,  4, 15],
       [11, 42,  4, 35, 15]])

In [40]:
ind = np.array([33,4,1,55,3])
m[ind > 10]


array([[33, 41, 45,  4, 15],
       [11, 42,  4, 35, 15]])