## Pruebas con la librería numpy

In [1]:
import numpy as np

In [2]:
%%timeit
arr = np.arange(1000000)
for _ in range(10): arr = arr * 2

17.4 ms ± 1.25 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
%%timeit
L = list(range(1000000))
for _ in range(10): L = [x*2 for x in L]

773 ms ± 29.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
arr1 = np.array([1,2,3,4,8.5])
print(arr1)
print(arr1.dtype)

[1.  2.  3.  4.  8.5]
float64


In [5]:
arr1.shape

(5,)

In [6]:
m = np.array(range(24)).reshape(6,-1)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
arr2 = np.array((1,2,3,4,5,6), dtype=np.uint8)
arr3 = np.array((1,-2,30,4,15,6), dtype="i1")
print(arr2)
print(arr3)


[1 2 3 4 5 6]
[ 1 -2 30  4 15  6]


In [12]:
arr4 = np.array(["1","3","5","8"], dtype=np.int8)
arr4

array([1, 3, 5, 8], dtype=int8)

In [13]:
arr5 = arr4.astype(np.float32)
arr5

array([1., 3., 5., 8.], dtype=float32)

In [14]:
arr6 = np.array([1,2,3,6.5, 6+8j])
arr6

array([1. +0.j, 2. +0.j, 3. +0.j, 6.5+0.j, 6. +8.j])

In [15]:
print(arr2)
print(arr3)

[1 2 3 4 5 6]
[ 1 -2 30  4 15  6]


In [16]:
r = arr2 + arr3
r

array([ 2,  0, 33,  8, 20, 12], dtype=int16)

In [17]:
m = np.zeros((3,4,5))
m

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [19]:
m2 = np.ones_like(m)
m2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [20]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
arr = np.random.randint(1,20, 15)
arr

array([ 3,  5,  5, 16, 17, 13,  2, 17,  8,  7, 17, 13, 19, 14,  2])

In [22]:
arr > 10

array([False, False, False,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True, False])

In [23]:
(arr > 10).sum()

8

In [24]:
arr[arr > 10]

array([16, 17, 13, 17, 17, 13, 19, 14])

In [25]:
arr[[0,1,2]]

array([3, 5, 5])

In [26]:
arr[(arr >= 5) & (arr <= 10)]

array([5, 5, 8, 7])

In [27]:
arr[(arr > 5) & (arr < 10)] = 5
arr

array([ 3,  5,  5, 16, 17, 13,  2, 17,  5,  5, 17, 13, 19, 14,  2])

In [28]:
m2 = np.random.randint(1,20, 25).reshape(5,-1)
m2

array([[ 9, 16,  4,  1, 13],
       [18,  3,  2,  4,  9],
       [ 5,  4, 18, 12, 19],
       [17,  1,  5, 14, 16],
       [17, 18, 18,  1, 11]])

In [29]:
m2[1:-1,1:-1]

array([[ 3,  2,  4],
       [ 4, 18, 12],
       [ 1,  5, 14]])

In [30]:
m2[0]

array([ 9, 16,  4,  1, 13])

In [31]:
m2[[4,2,1]]

array([[17, 18, 18,  1, 11],
       [ 5,  4, 18, 12, 19],
       [18,  3,  2,  4,  9]])

In [32]:
m2[[True,False,True,True,False]]

array([[ 9, 16,  4,  1, 13],
       [ 5,  4, 18, 12, 19],
       [17,  1,  5, 14, 16]])

In [33]:
arr2 = np.array((1,2,3,4,5,6), dtype=np.uint8)
arr3 = np.array((1,-2,30,4,15,6), dtype="i1")
print(arr2)
print(arr3)

[1 2 3 4 5 6]
[ 1 -2 30  4 15  6]


In [34]:
print(np.maximum(arr2, arr3))
print(np.minimum(arr2, arr3))

[ 1  2 30  4 15  6]
[ 1 -2  3  4  5  6]


In [ ]:
m1 = np.arange(9).reshape((3,3))
