## Pruebas con la librería numpy

In [1]:
import numpy as np

In [2]:
%%timeit
arr = np.arange(1000000)
for _ in range(10): arr = arr * 2

17.4 ms ± 1.25 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
%%timeit
L = list(range(1000000))
for _ in range(10): L = [x*2 for x in L]

773 ms ± 29.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
arr1 = np.array([1,2,3,4,8.5])
print(arr1)
print(arr1.dtype)

[1.  2.  3.  4.  8.5]
float64


In [5]:
arr1.shape

(5,)

In [6]:
m = np.array(range(24)).reshape(6,-1)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
arr2 = np.array((1,2,3,4,5,6), dtype=np.uint8)
arr3 = np.array((1,-2,30,4,15,6), dtype="i1")
print(arr2)
print(arr3)


[1 2 3 4 5 6]
[ 1 -2 30  4 15  6]


In [12]:
arr4 = np.array(["1","3","5","8"], dtype=np.int8)
arr4

array([1, 3, 5, 8], dtype=int8)

In [13]:
arr5 = arr4.astype(np.float32)
arr5

array([1., 3., 5., 8.], dtype=float32)