## Pruebas con la librería numpy

Objeto ndarray de numpy, función array, arrays multidimensionales, funciones de numpy, entrada/salida

In [3]:
import numpy as np

In [2]:
import random

In [8]:
np.__version__

'1.21.0'

In [9]:
%%timeit
# Ejecución con la lista
L = list(range(1000000))
for _ in range(10): L = [x*2 for x in L]

727 ms ± 32.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%%timeit
# Ejecución con array de numpy
arr = np.arange(1000000)
for _ in range(10): arr = arr * 2

16.1 ms ± 576 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
arr1 = np.array([1,2,3,45,6])
arr1

array([ 1,  2,  3, 45,  6])

In [12]:
arr1.dtype

dtype('int32')

In [13]:
arr2 = np.array((12.8, 5, 4, 2, 7.7))
arr2

array([12.8,  5. ,  4. ,  2. ,  7.7])

In [14]:
arr2.dtype

dtype('float64')

In [15]:
arr3 = np.array((12.8, 5, 4, 2, 7.7, 6+8j))
arr3

array([12.8+0.j,  5. +0.j,  4. +0.j,  2. +0.j,  7.7+0.j,  6. +8.j])

In [17]:
arr3.dtype

dtype('complex128')

In [18]:
arr4 = np.array(['55','66','23','9'], dtype=np.uint8)
arr4, arr4.dtype

(array([55, 66, 23,  9], dtype=uint8), dtype('uint8'))

In [19]:
arr5 = arr2.astype(np.float32)
arr5

array([12.8,  5. ,  4. ,  2. ,  7.7], dtype=float32)

In [20]:
arr5

array([12.8,  5. ,  4. ,  2. ,  7.7], dtype=float32)

In [24]:
arr5[1] = '11'

In [25]:
arr5

array([11. , 11. ,  4. ,  2. ,  7.7], dtype=float32)

In [27]:
m = np.arange(24).reshape(2,6,-1)
m

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [28]:
m = m + 5
m

array([[[ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24],
        [25, 26],
        [27, 28]]])