## Pruebas con la librería numpy

Objeto ndarray de numpy, función array, arrays multidimensionales, funciones de numpy, entrada/salida

In [3]:
import numpy as np

In [2]:
import random

In [8]:
np.__version__

'1.21.0'

In [9]:
%%timeit
# Ejecución con la lista
L = list(range(1000000))
for _ in range(10): L = [x*2 for x in L]

727 ms ± 32.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%%timeit
# Ejecución con array de numpy
arr = np.arange(1000000)
for _ in range(10): arr = arr * 2

16.1 ms ± 576 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
arr1 = np.array([1,2,3,45,6])
arr1

array([ 1,  2,  3, 45,  6])

In [12]:
arr1.dtype

dtype('int32')

In [13]:
arr2 = np.array((12.8, 5, 4, 2, 7.7))
arr2

array([12.8,  5. ,  4. ,  2. ,  7.7])

In [14]:
arr2.dtype

dtype('float64')

In [15]:
arr3 = np.array((12.8, 5, 4, 2, 7.7, 6+8j))
arr3

array([12.8+0.j,  5. +0.j,  4. +0.j,  2. +0.j,  7.7+0.j,  6. +8.j])

In [17]:
arr3.dtype

dtype('complex128')

In [18]:
arr4 = np.array(['55','66','23','9'], dtype=np.uint8)
arr4, arr4.dtype

(array([55, 66, 23,  9], dtype=uint8), dtype('uint8'))

In [19]:
arr5 = arr2.astype(np.float32)
arr5

array([12.8,  5. ,  4. ,  2. ,  7.7], dtype=float32)

In [20]:
arr5

array([12.8,  5. ,  4. ,  2. ,  7.7], dtype=float32)

In [30]:
arr5[1] = '11'

In [25]:
arr5

array([11. , 11. ,  4. ,  2. ,  7.7], dtype=float32)

In [27]:
m = np.arange(24).reshape(2,6,-1)
m

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [28]:
m = m + 5
m

array([[[ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24],
        [25, 26],
        [27, 28]]])

In [33]:
m.shape

(2, 6, 2)

In [32]:
arr6 = np.array(['55','66','23','9'], dtype="u2")
arr6, arr6.dtype

(array([55, 66, 23,  9], dtype=uint16), dtype('uint16'))

In [34]:
type(arr6)

numpy.ndarray

In [35]:
m2 = np.empty((5,6))
m2

array([[9.02914713e-312, 9.03941405e-312, 0.00000000e+000,
        0.00000000e+000, 1.60218763e-306, 5.02034658e+175],
       [9.44182489e+164, 3.88516746e-057, 1.90147343e-052,
        1.72483760e-047, 1.47763641e+248, 1.16096346e-028],
       [7.69165785e+218, 1.35617292e+248, 9.37868238e-047,
        2.48565090e+184, 1.08467507e-042, 1.21097151e-071],
       [4.30514846e-096, 6.32299154e+233, 6.48224638e+170,
        5.22411352e+257, 5.74020278e+180, 8.37174974e-144],
       [1.41529402e+161, 6.00736899e-067, 5.16823469e+097,
        7.72504235e-043, 4.26724339e+126, 2.62459060e-306]])

In [36]:
n3 = np.ones_like(m2)
n3

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
m = np.eye(6)
m

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [38]:
arr = np.random.randint(1,30,20)
arr

array([26, 20,  5,  1, 18,  6,  5, 14, 18, 28, 24, 15, 14, 21, 14, 23,  5,
       14, 15, 12])

In [39]:
arr > 20

array([ True, False, False, False, False, False, False, False, False,
        True,  True, False, False,  True, False,  True, False, False,
       False, False])

In [40]:
arr[arr > 20]

array([26, 28, 24, 21, 23])

In [41]:
arr[arr > 20] = 20
arr

array([20, 20,  5,  1, 18,  6,  5, 14, 18, 20, 20, 15, 14, 20, 14, 20,  5,
       14, 15, 12])

In [42]:
arr[(arr >= 15) & (arr <= 20)]

array([20, 20, 18, 18, 20, 20, 15, 20, 20, 15])

In [43]:
arr[(arr < 10) | (arr > 15)]

array([20, 20,  5,  1, 18,  6,  5, 18, 20, 20, 20, 20,  5])

In [46]:
arr1 = np.random.randint(1,30,20)
arr2 = np.random.randint(1,30,20)
arr1 + arr2

array([23, 32, 31, 42,  9, 19, 26, 35, 33, 25, 33, 24, 30, 46, 35, 21, 46,
       53, 19, 44])

In [47]:
# Generar una matriz cuadrada de 7 x 7 y quitar todo el contorno de la matriz: 5x5
m = np.random.randint(1,30,(7,7))
m

array([[ 5, 21, 17, 12,  4, 24,  2],
       [23, 23, 24, 27, 20, 17,  9],
       [ 9, 20,  9,  2, 26, 28,  9],
       [ 7, 10, 29, 21, 23, 12, 13],
       [25, 26,  2, 10, 17, 27, 17],
       [20, 18, 10, 28,  8, 10, 21],
       [ 8,  9, 13,  7, 16,  4, 29]])

In [48]:
m[1:-1,1:-1]

array([[23, 24, 27, 20, 17],
       [20,  9,  2, 26, 28],
       [10, 29, 21, 23, 12],
       [26,  2, 10, 17, 27],
       [18, 10, 28,  8, 10]])

In [49]:
m[0]

array([ 5, 21, 17, 12,  4, 24,  2])

In [50]:
m[[0,3,2]]

array([[ 5, 21, 17, 12,  4, 24,  2],
       [ 7, 10, 29, 21, 23, 12, 13],
       [ 9, 20,  9,  2, 26, 28,  9]])

In [51]:
m[0][0]

5

In [52]:
ind = [True, True, False, False, True, False, True]
m[ind]

array([[ 5, 21, 17, 12,  4, 24,  2],
       [23, 23, 24, 27, 20, 17,  9],
       [25, 26,  2, 10, 17, 27, 17],
       [ 8,  9, 13,  7, 16,  4, 29]])

In [53]:
m[1] = 100
m

array([[  5,  21,  17,  12,   4,  24,   2],
       [100, 100, 100, 100, 100, 100, 100],
       [  9,  20,   9,   2,  26,  28,   9],
       [  7,  10,  29,  21,  23,  12,  13],
       [ 25,  26,   2,  10,  17,  27,  17],
       [ 20,  18,  10,  28,   8,  10,  21],
       [  8,   9,  13,   7,  16,   4,  29]])

In [54]:
for i in range(7):
    m[i] = i
m

array([[0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6]])