## Pruebas con la librería numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.4'

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
type(arr)

numpy.ndarray

In [6]:
%%timeit
my_arr = np.arange(1000000)
for _ in range(10): my_arr2 = my_arr * 2

14.8 ms ± 305 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
%%timeit
my_list = list(range(1000000))
for _ in range(10): my_list2 = [x*2 for x in my_list]

765 ms ± 46.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
arr2 = np.arange(25).reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
arr3 = arr2 * 5
arr3

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [11]:
arr3.shape

(5, 5)

In [12]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [13]:
# Inferencia de tipos
a2 = np.array([1,2,3.1,4])
a2

array([1. , 2. , 3.1, 4. ])

In [15]:
a3 = np.array([1,2,3.1,4+3j])
a3

array([1. +0.j, 2. +0.j, 3.1+0.j, 4. +3.j])

In [19]:
# Indicar el tipo al construir el array
a4 = np.array(['34','7','9','10'], dtype=np.uint8)
print(a4)
print(a4.dtype)

[34  7  9 10]
uint8


In [17]:
# Forzar conversión a otro tipo
a5 = a4.astype(np.int16)
a5.dtype

dtype('int16')

In [20]:
a6 = a5.astype('u4')
a6.dtype

dtype('uint32')

In [21]:
ceros = np.zeros((2,3,4))
ceros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [22]:
unos = np.ones_like(ceros)
unos

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [23]:
arr = np.array([1,2,3,5,4,33,2,1,2,66,754,9])
v = arr > 10
v

array([False, False, False, False, False,  True, False, False, False,
        True,  True, False])

In [24]:
v2 = arr[arr > 10]
v2

array([ 33,  66, 754])

In [26]:
# Filtrar mediante un intervalo: & and, | or
v3 = arr[(arr > 2) & (arr < 10)]
v3

array([3, 5, 4, 9])

In [28]:
arr1 = np.random.randint(1,10,20)
arr1

array([2, 9, 6, 2, 8, 8, 8, 4, 6, 9, 2, 8, 9, 3, 3, 3, 6, 6, 1, 4])

In [29]:
arr2 = np.random.randint(1,10,20)
arr2

array([9, 6, 6, 5, 4, 2, 7, 4, 9, 3, 7, 6, 2, 6, 8, 9, 9, 6, 3, 3])

In [31]:
arr1 + arr2

array([11, 15, 12,  7, 12, 10, 15,  8, 15, 12,  9, 14, 11,  9, 11, 12, 15,
       12,  4,  7])

In [30]:
m = np.random.randint(1,10,(5,7))
m

array([[2, 9, 1, 8, 2, 3, 4],
       [3, 4, 5, 4, 9, 1, 3],
       [5, 8, 5, 8, 5, 6, 8],
       [2, 6, 8, 6, 8, 7, 8],
       [6, 7, 3, 7, 1, 9, 2]])

In [32]:
m = np.random.randint(1,10,(5,5))
m

array([[4, 6, 1, 9, 9],
       [6, 1, 3, 3, 7],
       [1, 8, 7, 5, 6],
       [9, 9, 7, 6, 3],
       [9, 6, 6, 1, 6]])

In [34]:
m2 = m[1:-1,1:-1]

In [37]:
arr1 = np.random.randint(1,10,15)
arr2 = np.random.randint(1,10,20)
arr1 < arr2[:15]

array([False,  True, False,  True, False, False, False,  True,  True,
       False,  True,  True, False, False, False])

In [39]:
arr1.add(arr2)

AttributeError: 'numpy.ndarray' object has no attribute 'add'

In [40]:
np.where(arr1 < arr2, True, False)

ValueError: operands could not be broadcast together with shapes (15,) (20,) 

In [41]:
m

array([[4, 6, 1, 9, 9],
       [6, 1, 3, 3, 7],
       [1, 8, 7, 5, 6],
       [9, 9, 7, 6, 3],
       [9, 6, 6, 1, 6]])

In [42]:
m[0]

array([4, 6, 1, 9, 9])

In [43]:
m[[0,2,4]]

array([[4, 6, 1, 9, 9],
       [1, 8, 7, 5, 6],
       [9, 6, 6, 1, 6]])

In [44]:
m[[4,0,2]]

array([[9, 6, 6, 1, 6],
       [4, 6, 1, 9, 9],
       [1, 8, 7, 5, 6]])

In [45]:
m.T

array([[4, 6, 1, 9, 9],
       [6, 1, 8, 9, 6],
       [1, 3, 7, 7, 6],
       [9, 3, 5, 6, 1],
       [9, 7, 6, 3, 6]])

In [46]:
arr = np.abs([1,-6, -8, 2, 1])
arr

array([1, 6, 8, 2, 1])

In [47]:
arr.dtype

dtype('int32')

In [48]:
arr = np.abs((1,-6, -8, 2, 1))
arr

array([1, 6, 8, 2, 1])

In [49]:
print(arr1)
print(arr2)

[9 1 6 4 7 3 9 5 3 3 5 6 7 4 9]
[7 7 6 7 4 3 6 8 6 3 6 8 1 3 1 2 7 1 3 7]


In [50]:
np.less(arr1, arr2)

ValueError: operands could not be broadcast together with shapes (15,) (20,) 

In [51]:
arr1.shape

(15,)

In [52]:
m = np.random.randn(4,4)
m

array([[ 0.46877269, -0.32792933,  0.56639745, -0.27846983],
       [ 0.36315579, -0.52390758, -0.44617817, -1.59145073],
       [-0.20124539, -0.06778286, -0.84971109, -0.05305019],
       [-0.17547595,  0.08877847, -0.90459555, -0.96662732]])

In [ ]:
m2 = np.where(m > 0, m,  )