### Pruebas con la librería numpy

In [1]:
import numpy as np

In [2]:
L = list(range(1000000))
arr = np.arange(1000000)

In [4]:
%%timeit
for _ in range(10): L2 = [i * 2 for i in L]


654 ms ± 31.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%%timeit
for _ in range(10): arr2 = arr * 2

14.6 ms ± 199 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
arr1 = np.array([1.8, 5, 7.0, 2.3, 1])
arr1

array([1.8, 5. , 7. , 2.3, 1. ])

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2 = np.array([1,2,3,4,5], dtype=np.uint8)
arr3 = np.array([1,2,3,4,5], dtype="u2")

In [12]:
print(arr2.dtype)
print(arr3.dtype)

uint8
uint16


In [13]:
arr3 = np.array(['1','2','3','4','5'], dtype="u2")
arr3

array([1, 2, 3, 4, 5], dtype=uint16)

In [14]:
arr4 = arr3.astype(np.float64)
arr4

array([1., 2., 3., 4., 5.])

In [15]:
m = np.zeros((2,3,4))
m

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
m2 = np.ones_like(m)
m2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
m =  np.random.randint(1,100,20)
m

array([63, 25, 42, 19, 59, 50, 97,  8, 26, 58,  5, 66, 45, 32, 18, 76, 15,
       59, 15, 77])

In [19]:
m > 15

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False,  True])

In [21]:
(m > 5).sum()

19

In [22]:
m[m > 60] =  60
m

array([60, 25, 42, 19, 59, 50, 60,  8, 26, 58,  5, 60, 45, 32, 18, 60, 15,
       59, 15, 60])

In [23]:
m[(m > 10) & (m < 40)]

array([25, 19, 26, 32, 18, 15, 15])

In [25]:
m = np.arange(25).reshape(-1, 5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# quitar el contorno de la matriz con slicing:
m[1:-1, 1:-1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [27]:
m[[1,2]]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
m[[True, True,False, False, True]]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [30]:
col1 = np.random.randint(1,100, 30)
col2 = np.random.randint(1,100, 30)
print(col1)
print()
print(col2)

[10 51 18 14 98 74 39 82  4 39 14 22 28 87 43 56 51 17 73 69 76 46 85  6
 20 95 42 86 92 62]

[52 22 24 88 57 47 57 71 55 72 51 35  4 78 99  1  9  2 75 70 24 88 54 51
 45 63 35 45 70 50]


In [31]:
np.maximum(col1, col2)

array([52, 51, 24, 88, 98, 74, 57, 82, 55, 72, 51, 35, 28, 87, 99, 56, 51,
       17, 75, 70, 76, 88, 85, 51, 45, 95, 42, 86, 92, 62])

In [32]:
np.minimum(col1, col2)

array([10, 22, 18, 14, 57, 47, 39, 71,  4, 39, 14, 22,  4, 78, 43,  1,  9,
        2, 73, 69, 24, 46, 54,  6, 20, 63, 35, 45, 70, 50])

In [33]:
col1 + col2

array([ 62,  73,  42, 102, 155, 121,  96, 153,  59, 111,  65,  57,  32,
       165, 142,  57,  60,  19, 148, 139, 100, 134, 139,  57,  65, 158,
        77, 131, 162, 112])

In [34]:
col1 > col2

array([False,  True, False, False,  True,  True, False,  True, False,
       False, False, False,  True,  True, False,  True,  True,  True,
       False, False,  True, False,  True, False, False,  True,  True,
        True,  True,  True])

In [35]:
# Función where:
m = np.random.randn(5,5)
m

array([[ 1.33266099, -0.83602452, -0.44379874,  1.02491745, -0.64809432],
       [-2.05482505,  0.54628733, -0.98044649,  0.9556619 ,  0.42074705],
       [-1.38549726, -1.28806806, -0.56807396,  1.14577874, -0.03083573],
       [ 0.5001852 , -0.00515195, -0.42179108,  1.3932677 , -0.46202511],
       [-0.77956875, -0.30466409, -0.15358123, -0.10833786,  0.28341095]])

In [36]:
m = m * 10
m

array([[ 13.32660993,  -8.3602452 ,  -4.43798739,  10.24917454,
         -6.48094316],
       [-20.5482505 ,   5.46287327,  -9.80446485,   9.55661899,
          4.20747045],
       [-13.85497262, -12.88068055,  -5.68073956,  11.45778738,
         -0.30835732],
       [  5.00185197,  -0.05151946,  -4.21791078,  13.93267701,
         -4.62025109],
       [ -7.79568754,  -3.04664095,  -1.53581226,  -1.08337864,
          2.83410954]])

In [38]:
n = np.where(m > 0, m, m * -1)
n


array([[13.32660993,  8.3602452 ,  4.43798739, 10.24917454,  6.48094316],
       [20.5482505 ,  5.46287327,  9.80446485,  9.55661899,  4.20747045],
       [13.85497262, 12.88068055,  5.68073956, 11.45778738,  0.30835732],
       [ 5.00185197,  0.05151946,  4.21791078, 13.93267701,  4.62025109],
       [ 7.79568754,  3.04664095,  1.53581226,  1.08337864,  2.83410954]])

In [39]:
arr1 = np.random.randint(1,10,10)
arr2 = np.random.randint(1,10,12)
print(arr1)
print(arr2)



[3 4 4 8 6 7 6 3 3 8]
[3 1 7 6 1 4 3 5 5 5 1 5]


In [40]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (10,) (12,) 

In [44]:
arr3 = np.abs((-1, -7, 3.8, -2.7))
arr3

array([1. , 7. , 3.8, 2.7])

In [45]:
m = np.random.randint(1,30,(4,6))
m

array([[21, 14,  2, 11, 10,  8],
       [25, 25, 25, 19, 19,  3],
       [12, 26,  6, 13, 10,  1],
       [ 8, 24, 25,  4, 29,  9]])

In [46]:
m.mean(axis=1) # por filas

array([11.        , 19.33333333, 11.33333333, 16.5       ])

In [47]:
m.mean()

14.541666666666666

In [48]:
m.mean(axis=0) # por cols

array([16.5 , 22.25, 14.5 , 11.75, 17.  ,  5.25])