### Pruebas con la librería numpy

In [1]:
import numpy as np

In [2]:
L = list(range(1000000))
arr = np.arange(1000000)

In [4]:
%%timeit
for _ in range(10): L2 = [i * 2 for i in L]


654 ms ± 31.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%%timeit
for _ in range(10): arr2 = arr * 2

14.6 ms ± 199 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
arr1 = np.array([1.8, 5, 7.0, 2.3, 1])
arr1

array([1.8, 5. , 7. , 2.3, 1. ])

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2 = np.array([1,2,3,4,5], dtype=np.uint8)
arr3 = np.array([1,2,3,4,5], dtype="u2")

In [12]:
print(arr2.dtype)
print(arr3.dtype)

uint8
uint16


In [13]:
arr3 = np.array(['1','2','3','4','5'], dtype="u2")
arr3

array([1, 2, 3, 4, 5], dtype=uint16)

In [14]:
arr4 = arr3.astype(np.float64)
arr4

array([1., 2., 3., 4., 5.])

In [15]:
m = np.zeros((2,3,4))
m

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
m2 = np.ones_like(m)
m2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
m =  np.random.randint(1,100,20)
m

array([63, 25, 42, 19, 59, 50, 97,  8, 26, 58,  5, 66, 45, 32, 18, 76, 15,
       59, 15, 77])

In [19]:
m > 15

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False,  True])

In [21]:
(m > 5).sum()

19

In [22]:
m[m > 60] =  60
m

array([60, 25, 42, 19, 59, 50, 60,  8, 26, 58,  5, 60, 45, 32, 18, 60, 15,
       59, 15, 60])